[workspace]
authors = ["Will Robertson <wspr81@gmail.com>"]
channels = ["conda-forge"]
name = "au-fe-template"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
fenics-dolfinx = "*"
mpich = "*"
pyvista = "*"
gmsh = ">=4.15.0,<5"
